#!/bin/bash

## Download and prep the dataset

./get-data.sh


## setup Lupyter Lab extensions 

LABEXT_INSTALL_OPTS="--minimize=False --dev-build=False"


# plotly -- https://plotly.com/python/getting-started
jupyter labextension install ${LABEXT_INSTALL_OPTS} jupyterlab-plotly
jupyter labextension install ${LABEXT_INSTALL_OPTS} @jupyter-widgets/jupyterlab-manager plotlywidget

# jupyterlab-code-formatter -- https://github.com/ryantam626/jupyterlab_code_formatter
jupyter labextension install ${LABEXT_INSTALL_OPTS} @ryantam626/jupyterlab_code_formatter
jupyter serverextension enable --py jupyterlab_code_formatter

# hide-code -- https://github.com/kirbs-/hide_code
jupyter nbextension install --user --py hide_code
jupyter nbextension enable --py hide_code
jupyter serverextension enable --py hide_code
